-- ============================================================
-- Lakay Ago / Aroo — Combined Supabase PostgreSQL Schema
--
-- Modules:
-- 1. Attendance / Payroll / Leave
-- 2. Inventory: Production -> Kitchen -> Menu
-- 3. Sales
-- 4. Expenses
--
-- Restaurants:
-- - Aroo
-- - Lakay Ago
--
-- IMPORTANT INVENTORY RELATIONSHIP RULE:
-- Each restaurant has its own Production, Kitchen, and Inventory
-- records.
--
-- However, inventory relationships and stock transactions may
-- cross restaurant boundaries.
--
-- Example:
-- Aroo Kitchen can receive stock from Lakay Ago Production.
--
-- Therefore:
-- - restaurants_id identifies the restaurant that owns the row.
-- - kitchen_id / production_id / inventory_id identify the
-- specific related record.
-- - No composite same-restaurant foreign keys are used.
--
-- CROSS-RESTAURANT OWNERSHIP RULE (stock_transactions):
-- A cross-restaurant transfer touches two restaurants at once
-- (Production's and Kitchen's), but stock_transactions.restaurants_id
-- can only hold one value. To remove any ambiguity about which side
-- "wins", a trigger (see below, near the stock_transactions table)
-- always DERIVES restaurants_id from the destination side of the
-- transaction and overwrites whatever value was supplied:
-- - TRANSFER / SELF_PRODUCE: destination is the Kitchen, so
-- restaurants_id := kitchen_stock.restaurants_id for that kitchen_id.
-- - SALE: destination is the Menu (inventory), so
-- restaurants_id := inventory.restaurants_id for that inventory_id.
-- This makes the rule enforced by the database itself rather than
-- something every insert has to get right on its own — two different
-- inserts for the same real-world transfer can no longer disagree.
--
-- Passwords:
-- users.password must contain a bcrypt hash generated by the
-- application layer. Plaintext passwords must NEVER be stored.
--
-- RLS:
-- RLS is intentionally not enabled in this schema.
-- ============================================================


-- ============================================================
-- 1. RESTAURANTS
-- ============================================================

create table if not exists restaurants (
    restaurants_id bigint generated always as identity primary key,

    name text not null unique,

    created_at timestamptz not null default now()
);

comment on table restaurants is
'The restaurant branches whose data is tracked.';


-- ============================================================
-- 2. USERS
-- ============================================================
-- App-level accounts:
-- Admin / SuperAdmin / Staff
--
-- restaurant_id is nullable because a SuperAdmin may not be
-- scoped to a single restaurant.
-- ============================================================

create table if not exists users (
    user_id bigint generated always as identity primary key,

    -- user-visible restaurant scope; options limited to the two known restaurants or Both
    restaurant text not null default 'Both'
        check (restaurant in ('Lakay Ago', 'Aroo', 'Both')),

    name text not null,

    username text not null unique,

    email text not null unique,

    -- Stores a bcrypt hash, NOT a plaintext password.
    password text not null,

    role text not null
        check (role in ('Admin', 'SuperAdmin', 'Staff')),

    created_at timestamptz not null default now()
);

comment on table users is
'App-level user accounts and roles. password must contain a bcrypt hash generated by the application layer, never plaintext. The `restaurant` column contains the user scope: Lakay Ago, Aroo, or Both.';


-- ============================================================
-- 3. EMPLOYEES
-- ============================================================

create table if not exists employees (
    employee_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    source_employee_id bigint not null,

    name text not null,

    department text,

    basic_salary numeric(10,2),

    status text not null default 'active'
        check (status in ('active', 'inactive', 'fired')),

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    unique (restaurant_id, source_employee_id)
);

comment on table employees is
'Employee master list, scoped per restaurant since employee IDs are only unique within each restaurant.';

create index if not exists idx_employees_restaurant
    on employees (restaurant_id);

create index if not exists idx_employees_status
    on employees (status);


-- ============================================================
-- 4. LEAVE TYPES
-- ============================================================

create table if not exists leave_types (
    leave_type_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    name text not null,

    created_at timestamptz not null default now(),

    unique (restaurant_id, name)
);

comment on table leave_types is
'Leave categories available at a restaurant.';

create index if not exists idx_leave_types_restaurant
    on leave_types (restaurant_id);


-- ============================================================
-- 5. EMPLOYEE LEAVE BALANCES
-- ============================================================

create table if not exists employee_leave_balances (
    leave_bal_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    employee_id bigint not null
        references employees(employee_id)
        on delete cascade,

    leave_type_id bigint not null
        references leave_types(leave_type_id)
        on delete cascade,

    number_of_leave numeric(5,1) not null default 0
        check (number_of_leave >= 0),

    available_leave numeric(5,1) not null default 0
        check (available_leave >= 0),

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    unique (employee_id, leave_type_id)
);

comment on table employee_leave_balances is
'Per-employee leave credit and available balance, broken out by leave type.';

create index if not exists idx_leave_balances_employee
    on employee_leave_balances (employee_id);

create index if not exists idx_leave_balances_restaurant
    on employee_leave_balances (restaurant_id);


-- ============================================================
-- 6. LEAVE REQUESTS
-- ============================================================

create table if not exists leave_requests (
    leave_request_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    employee_id bigint not null
        references employees(employee_id)
        on delete cascade,

    leave_type_id bigint
        references leave_types(leave_type_id)
        on delete set null,

    employee_name text not null,

    department text,

    leave_type_name text not null,

    start_date date not null,

    end_date date not null,

    days numeric(5,1) not null
        check (days > 0),

    reason text,

    status text not null default 'Pending'
        check (status in ('Pending', 'Approved', 'Rejected')),

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    check (end_date >= start_date)
);

comment on table leave_requests is
'Individual leave applications and their approval status.';

create index if not exists idx_leave_requests_restaurant
    on leave_requests (restaurant_id);

create index if not exists idx_leave_requests_employee
    on leave_requests (employee_id);

create index if not exists idx_leave_requests_status
    on leave_requests (status);

create index if not exists idx_leave_requests_leave_type
    on leave_requests (leave_type_id);


-- ============================================================
-- 7. DEDUCTION TYPES
-- ============================================================

create table if not exists deduction_types (
    deduction_type_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    name text not null,

    is_statutory boolean not null default true,

    description text,

    created_at timestamptz not null default now(),

    unique (restaurant_id, name)
);

comment on table deduction_types is
'Statutory contribution deduction categories available at a restaurant.';

create index if not exists idx_deduction_types_restaurant
    on deduction_types (restaurant_id);


-- ============================================================
-- 8. REPORT PERIODS
-- ============================================================

create table if not exists report_periods (
    report_period_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    period_start date not null,

    period_end date not null,

    tabulation_date date,

    source_file text,

    created_at timestamptz not null default now(),

    unique (restaurant_id, period_start, period_end)
);

comment on table report_periods is
'One row per attendance report export for a restaurant.';


-- ============================================================
-- 9. DEDUCTIONS
-- ============================================================

create table if not exists deductions (
    deduction_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    employee_id bigint not null
        references employees(employee_id)
        on delete cascade,

    deduction_type_id bigint not null
        references deduction_types(deduction_type_id)
        on delete cascade,

    period_id bigint
        references report_periods(report_period_id)
        on delete set null,

    amount numeric(10,2) not null default 0,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    unique (employee_id, deduction_type_id, period_id)
);

comment on table deductions is
'Per-employee statutory deduction amounts, broken out per pay period.';

create index if not exists idx_deductions_employee
    on deductions (employee_id);

create index if not exists idx_deductions_period
    on deductions (period_id);

create index if not exists idx_deductions_restaurant
    on deductions (restaurant_id);


-- ============================================================
-- 10. CASH ADVANCES
-- ============================================================

create table if not exists cash_advances (
    cash_advances_id bigint generated always as identity primary key,

    employee_id bigint not null
        references employees(employee_id)
        on delete cascade,

    restaurant text not null default 'Both'
        check (restaurant in ('Lakay Ago', 'Aroo', 'Both')),

    amount numeric(10,2) not null default 0
        check (amount >= 0),

    date_requested date not null,

    date_released date,

    status text not null default 'pending'
        check (status in ('pending', 'approved', 'released', 'deducted', 'cancelled')),

    approved_by bigint
        references employees(employee_id)
        on delete set null,

    remarks text,

    balance_remaining numeric(10,2) not null default 0
        check (balance_remaining >= 0),

    is_fully_paid boolean not null default false,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);

comment on table cash_advances is
'Cash advances issued to employees and repaid through payroll deductions.';

create table if not exists cash_advance_payments (
    cash_advance_payments_id bigint generated always as identity primary key,

    cash_advances_id bigint not null
        references cash_advances(cash_advances_id)
        on delete cascade,

    report_period_id bigint
        references report_periods(report_period_id)
        on delete set null,

    amount_deducted numeric(10,2) not null default 0
        check (amount_deducted >= 0),

    created_at timestamptz not null default now()
);

comment on table cash_advance_payments is
'Payroll-period deductions applied against an employee cash advance.';

create or replace function refresh_cash_advance_totals()
returns trigger as $$
begin
    update cash_advances ca
    set
        balance_remaining = greatest(
            ca.amount - coalesce((
                select sum(cap.amount_deducted)
                from cash_advance_payments cap
                where cap.cash_advances_id = ca.cash_advances_id
            ), 0), 0),
        is_fully_paid = (
            ca.amount - coalesce((
                select sum(cap.amount_deducted)
                from cash_advance_payments cap
                where cap.cash_advances_id = ca.cash_advances_id
            ), 0)
        ) <= 0,
        updated_at = now()
    where ca.cash_advances_id = coalesce(new.cash_advances_id, old.cash_advances_id);

    return coalesce(new, old);
end;
$$ language plpgsql;

create trigger if not exists cash_advance_payment_balance_refresh
after insert or update of amount_deducted, delete on cash_advance_payments
for each row
execute procedure refresh_cash_advance_totals();

create index if not exists idx_cash_advances_employee
    on cash_advances (employee_id);

create index if not exists idx_cash_advances_status
    on cash_advances (status);

create index if not exists idx_cash_advance_payments_advance
    on cash_advance_payments (cash_advances_id);

create index if not exists idx_cash_advance_payments_period
    on cash_advance_payments (report_period_id);

-- ============================================================
-- 11. ATTENDANCE
-- ============================================================

create table if not exists attendance (
    attendance_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    employee_id bigint not null
        references employees(employee_id)
        on delete cascade,

    period_id bigint
        references report_periods(report_period_id)
        on delete set null,

    work_date date not null,

    first_on_duty time,

    first_off_duty time,

    second_on_duty time,

    second_off_duty time,

    late_minutes integer not null default 0,

    leave_early_minutes integer not null default 0,

    total_minutes integer not null default 0,

    is_absent boolean not null default false,

    is_halfday boolean not null default false,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    unique (employee_id, work_date)
);

comment on table attendance is
'Daily punch times and exception minutes per employee per day.';

create index if not exists idx_attendance_employee_date
    on attendance (employee_id, work_date);

create index if not exists idx_attendance_restaurant
    on attendance (restaurant_id);


-- ============================================================
-- 11. AUDIT LOGS
-- ============================================================

create table if not exists audit_logs (
    log_id bigint generated always as identity primary key,

    user_id bigint
        references users(user_id)
        on delete set null,

    restaurant_id bigint
        references restaurants(restaurants_id)
        on delete set null,

    action text not null,

    table_name text,

    record_id text,

    old_data jsonb,

    new_data jsonb,

    description text,

    created_at timestamptz not null default now()
);

comment on table audit_logs is
'Activity log of user actions across the app.';

create index if not exists idx_audit_logs_user
    on audit_logs (user_id);

create index if not exists idx_audit_logs_table_record
    on audit_logs (table_name, record_id);

create index if not exists idx_audit_logs_created_at
    on audit_logs (created_at);

create index if not exists idx_audit_logs_restaurant
    on audit_logs (restaurant_id);


-- ============================================================
-- INVENTORY MODULE
-- Production -> Kitchen -> Menu
--
-- CROSS-RESTAURANT INTERACTIONS ARE ALLOWED.
-- ============================================================


-- ============================================================
-- 12. EXPENSES
-- ============================================================

create table if not exists expenses (
    expense_id bigint generated always as identity primary key,

    restaurant_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    name text not null,

    amount numeric(10,2) not null
        check (amount >= 0),

    created_at timestamptz not null default now()
);

comment on table expenses is
'Recorded business expenses scoped to a specific restaurant.';

create index if not exists idx_expenses_restaurant
    on expenses (restaurant_id);

create index if not exists idx_expenses_created_at
    on expenses (created_at);


-- ============================================================
-- 13. PRODUCTION STOCK
-- ============================================================

create table if not exists production_stock (
    production_id bigint generated always as identity primary key,

    restaurants_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    product text not null,

    department text not null default 'Production'
        check (department = 'Production'),

    stock numeric(10,2) not null default 0
        check (stock >= 0),

    created_at timestamptz not null default now(),

    unique (restaurants_id, product)
);

comment on table production_stock is
'Production stock belonging to a specific restaurant. Production stock may be transferred to kitchens belonging to either the same or another restaurant.';

create index if not exists idx_production_stock_restaurant
    on production_stock (restaurants_id);

create index if not exists idx_production_stock_product
    on production_stock (product);


-- ============================================================
-- 14. KITCHEN STOCK
-- ============================================================

create table if not exists kitchen_stock (
    kitchen_id bigint generated always as identity primary key,

    restaurants_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    product text not null,

    department text not null default 'Kitchen'
        check (department = 'Kitchen'),

    stock numeric(10,2) not null default 0
        check (stock >= 0),

    created_at timestamptz not null default now(),

    unique (restaurants_id, product)
);

comment on table kitchen_stock is
'Kitchen stock belonging to a specific restaurant. Kitchen stock may receive stock from Production belonging to either the same or another restaurant.';

create index if not exists idx_kitchen_stock_restaurant
    on kitchen_stock (restaurants_id);

create index if not exists idx_kitchen_stock_product
    on kitchen_stock (product);


-- ============================================================
-- 15. INVENTORY
--
-- Each linked Kitchen Stock item can correspond to exactly
-- one Inventory item.
--
-- IMPORTANT:
-- restaurants_id and kitchen_id are intentionally independent.
-- The referenced Kitchen Stock may belong to another restaurant.
-- ============================================================

create table if not exists inventory (
    inventory_id bigint generated always as identity primary key,

    restaurants_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    kitchen_id bigint
        references kitchen_stock(kitchen_id)
        on delete set null,

    name text,

    price numeric(10,2) not null
        check (price >= 0),

    stock numeric(10,2)
        check (stock is null or stock >= 0),

    category text not null
        check (category in ('Menu Item', 'Others')),

    is_archived boolean not null default false,

    created_at timestamptz not null default now(),

    -- Menu Item must be linked to Kitchen Stock.
    check (
        category <> 'Menu Item'
        or kitchen_id is not null
    ),

    -- Linked Inventory rows derive name/stock from Kitchen Stock.
    -- Standalone rows must contain their own name/stock.
    check (
        (
            kitchen_id is not null
            and name is null
            and stock is null
        )
        or
        (
            kitchen_id is null
            and name is not null
            and stock is not null
        )
    )
);

comment on table inventory is
'Restaurant-scoped Inventory catalog. A linked Inventory item derives its name and stock from a Kitchen Stock item. The Kitchen Stock may belong to a different restaurant because cross-restaurant relationships are intentionally allowed.';

-- One Kitchen Stock item -> one Inventory item.
create unique index if not exists uq_inventory_kitchen
    on inventory (kitchen_id)
    where kitchen_id is not null;

create index if not exists idx_inventory_restaurant
    on inventory (restaurants_id);

create index if not exists idx_inventory_category
    on inventory (category);

create index if not exists idx_inventory_archived
    on inventory (is_archived);


-- ============================================================
-- INVENTORY DISPLAY VIEW
-- ============================================================

create or replace view inventory_display
with (security_invoker = true)
as
select
    i.inventory_id,

    i.restaurants_id,

    coalesce(ks.product, i.name) as name,

    i.price,

    coalesce(ks.stock, i.stock) as stock,

    i.category,

    i.kitchen_id,

    i.is_archived,

    i.created_at

from inventory i

left join kitchen_stock ks
    on ks.kitchen_id = i.kitchen_id;

comment on view inventory_display is
'Resolved Inventory read view. Linked Inventory rows use the corresponding Kitchen Stock product and stock; standalone Inventory rows use their own name and stock. Cross-restaurant Kitchen relationships are allowed.';


-- ============================================================
-- 16. SALES
-- ============================================================

create table if not exists sales (
    sales_id bigint generated always as identity primary key,

    restaurants_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    inventory_id bigint
        references inventory(inventory_id)
        on delete set null,

    item text not null,

    cost numeric(10,2) not null
        check (cost >= 0),

    number_of_sales integer not null
        check (number_of_sales > 0),

    category text not null
        check (category in ('Menu Item', 'Others')),

    discount numeric(10,2) not null default 0
        check (discount >= 0),

    gross_amount numeric(10,2)
        generated always as (
            cost * number_of_sales
        ) stored,

    net_amount numeric(10,2)
        generated always as (
            cost * number_of_sales - discount
        ) stored,

    created_at timestamptz not null default now(),

    check (
        discount <= cost * number_of_sales
    )
);

comment on table sales is
'Restaurant-scoped sale transactions. item, category, and cost are frozen snapshots at the time of sale.';

create index if not exists idx_sales_restaurant
    on sales (restaurants_id);

create index if not exists idx_sales_inventory
    on sales (inventory_id);

create index if not exists idx_sales_category
    on sales (category);

create index if not exists idx_sales_created_at
    on sales (created_at);


-- ============================================================
-- 17. STOCK TRANSACTIONS
--
-- Cross-restaurant stock interaction is intentionally supported.
--
-- Example:
-- Aroo Kitchen can receive stock from Lakay Ago Production.
--
-- restaurants_id is NOT set by the caller — see the trigger
-- immediately below this table. It is always derived from the
-- destination side of the transaction: kitchen_stock's restaurant
-- for TRANSFER/SELF_PRODUCE, inventory's restaurant for SALE.
-- Whatever value is passed in on INSERT/UPDATE is overwritten, so
-- there is exactly one rule for "which restaurant owns this row",
-- enforced by the database rather than by application code.
-- ============================================================

create table if not exists stock_transactions (
    stock_transaction_id bigint generated always as identity primary key,

    restaurants_id bigint not null
        references restaurants(restaurants_id)
        on delete cascade,

    kitchen_id bigint
        references kitchen_stock(kitchen_id)
        on delete set null,

    production_id bigint
        references production_stock(production_id)
        on delete set null,

    inventory_id bigint
        references inventory(inventory_id)
        on delete set null,

    name text not null,

    transaction_type text not null
        check (
            transaction_type in (
                'TRANSFER',
                'SELF_PRODUCE',
                'SALE'
            )
        ),

    quantity numeric(10,2) not null
        check (quantity > 0),

    from_location text
        check (
            from_location in (
                'production',
                'kitchen'
            )
        ),

    to_location text
        check (
            to_location in (
                'kitchen',
                'menu'
            )
        ),

    performed_by text,

    created_at timestamptz not null default now(),

    -- TRANSFER:
    -- Production -> Kitchen
    --
    -- Production and Kitchen may belong to different restaurants.
    --
    -- SELF_PRODUCE:
    -- Internal Kitchen production
    --
    -- SALE:
    -- Kitchen -> Menu
    check (
        (
            transaction_type = 'TRANSFER'
            and from_location = 'production'
            and to_location = 'kitchen'
            and production_id is not null
            and kitchen_id is not null
            and inventory_id is null
        )
        or
        (
            transaction_type = 'SELF_PRODUCE'
            and from_location is null
            and to_location = 'kitchen'
            and production_id is null
            and kitchen_id is not null
            and inventory_id is null
        )
        or
        (
            transaction_type = 'SALE'
            and from_location = 'kitchen'
            and to_location = 'menu'
            and production_id is null
            and kitchen_id is not null
            and inventory_id is not null
        )
    )
);

comment on table stock_transactions is
'Restaurant-scoped audit trail of Production-to-Kitchen transfers, Kitchen self-production, and Menu sales. Production and Kitchen records may belong to different restaurants for cross-restaurant stock transfers. restaurants_id is auto-derived by trigger from the destination side — see trg_set_stock_transaction_restaurant below.';

create index if not exists idx_stock_transactions_restaurant
    on stock_transactions (restaurants_id);

create index if not exists idx_stock_transactions_kitchen
    on stock_transactions (kitchen_id);

create index if not exists idx_stock_transactions_production
    on stock_transactions (production_id);

create index if not exists idx_stock_transactions_inventory
    on stock_transactions (inventory_id);

create index if not exists idx_stock_transactions_type
    on stock_transactions (transaction_type);

create index if not exists idx_stock_transactions_created_at
    on stock_transactions (created_at);


-- ------------------------------------------------------------
-- Trigger: auto-derive stock_transactions.restaurants_id from
-- the destination side of the transaction, and enforce that a
-- TRANSFER moves the same item name (not a rename). See the
-- "CROSS-RESTAURANT OWNERSHIP RULE" note at the top of this file.
--
-- BEFORE INSERT/UPDATE runs prior to constraint checking, so this
-- overwrites NEW.restaurants_id (even if the caller passed null or
-- some other value) before the `not null` constraint is evaluated
-- — the caller does not need to know or supply the correct
-- restaurant at all, only the correct kitchen_id/inventory_id.
-- ------------------------------------------------------------
create or replace function set_stock_transaction_restaurant()
returns trigger as $$
declare
    v_production_product text;
    v_kitchen_product text;
begin
    if new.transaction_type in ('TRANSFER', 'SELF_PRODUCE') then
        select restaurants_id into new.restaurants_id
        from kitchen_stock
        where kitchen_id = new.kitchen_id;
    elsif new.transaction_type = 'SALE' then
        select restaurants_id into new.restaurants_id
        from inventory
        where inventory_id = new.inventory_id;
    end if;

    if new.restaurants_id is null then
        raise exception
            'Could not derive restaurants_id for stock_transactions row (transaction_type=%, kitchen_id=%, inventory_id=%)',
            new.transaction_type, new.kitchen_id, new.inventory_id;
    end if;

    -- A TRANSFER must move the same item, not rename it —
    -- production_stock.product and kitchen_stock.product must match,
    -- even across a cross-restaurant transfer.
    if new.transaction_type = 'TRANSFER' then
        select product into v_production_product
        from production_stock
        where production_id = new.production_id;

        select product into v_kitchen_product
        from kitchen_stock
        where kitchen_id = new.kitchen_id;

        if v_production_product is distinct from v_kitchen_product then
            raise exception
                'Product name mismatch on TRANSFER: production_stock.product = %, kitchen_stock.product = % (production_id=%, kitchen_id=%). A transfer must move the same item, not rename it.',
                v_production_product, v_kitchen_product, new.production_id, new.kitchen_id;
        end if;
    end if;

    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_set_stock_transaction_restaurant on stock_transactions;
create trigger trg_set_stock_transaction_restaurant
    before insert or update on stock_transactions
    for each row execute function set_stock_transaction_restaurant();


-- ============================================================
-- SEED THE TWO KNOWN RESTAURANTS
-- ============================================================

insert into restaurants (name)
values
    ('Aroo'),
    ('Lakay Ago')
on conflict (name) do nothing;


-- ============================================================
-- SEED STATUTORY DEDUCTION TYPES
-- ============================================================

insert into deduction_types (
    restaurant_id,
    name,
    is_statutory
)
select
    r.restaurants_id,
    dt.name,
    dt.is_statutory
from restaurants r
cross join (
    values
        ('SSS', true),
        ('PhilHealth', true),
        ('Pag-IBIG', true)
) as dt(name, is_statutory)
on conflict (restaurant_id, name) do nothing;


-- ============================================================
-- ROW LEVEL SECURITY
--
-- Enabled with NO policies. This is intentional and correct for
-- this app's architecture: the backend is the only thing that
-- talks to Supabase, always using the service_role key, which
-- bypasses RLS entirely regardless of policies. Enabling RLS with
-- zero policies denies all access to the anon/authenticated roles
-- — i.e. anyone using the public anon key directly (e.g. from
-- browser dev tools) gets nothing. That closes the "Unrestricted"
-- exposure without risking locking the backend out.
--
-- Only add real policies here if the browser ever needs to talk to
-- Supabase directly (e.g. Realtime subscriptions, a public
-- read-only page) — that path doesn't go through the backend, so
-- it would need its own scoped access rules.
-- ============================================================

alter table restaurants enable row level security;
alter table users enable row level security;
alter table employees enable row level security;
alter table leave_types enable row level security;
alter table employee_leave_balances enable row level security;
alter table leave_requests enable row level security;
alter table deduction_types enable row level security;
alter table deductions enable row level security;
alter table report_periods enable row level security;
alter table attendance enable row level security;
alter table audit_logs enable row level security;
alter table expenses enable row level security;
alter table production_stock enable row level security;
alter table kitchen_stock enable row level security;
alter table inventory enable row level security;
alter table sales enable row level security;
alter table stock_transactions enable row level security;