begin;

alter table public.sub_services
drop constraint if exists sub_services_service_id_fkey;

alter table public.sub_services
drop column if exists service_id;

create table if not exists public.service_sub_services (
  service_sub_service_id bigint generated by default as identity primary key,
  service_id bigint not null references public.services (service_id) on delete cascade,
  sub_service_id bigint not null references public.sub_services (sub_service_id) on delete restrict,
  unique (service_id, sub_service_id)
);

create index if not exists idx_service_sub_services_service_id
  on public.service_sub_services (service_id);

create index if not exists idx_service_sub_services_sub_service_id
  on public.service_sub_services (sub_service_id);

commit;
